# ChatGPT HiLetgo level-shifter DIN mount — Cable Clamp remix
# Design version: 1
# VERSIONING RULE: Increment DESIGN_VERSION on every repository check-in of this file.
#
# This is a separate design from ChatGPT_HiLetgo_Level_Shifter_DIN_Mount.scad.
# It is based on the user-supplied DIN_Rail_Cable_Clamp.step and preserves the
# original DIN rail snap/release geometry while replacing the cable-management
# prongs with a snap-in cradle for the ~15.3 x 12.6 x 1.6 mm HiLetgo board.
#
# Original DIN Rail Cable Clamp design: mdkendall / Thingiverse 2613804.
# The original design is distributed as Creative Commons Attribution (CC BY).
#
import cadquery as cq
from cadquery import exporters
from pathlib import Path

DESIGN_VERSION = 1
HERE = Path(__file__).resolve().parent
SOURCE = HERE / 'DIN_Rail_Cable_Clamp.step'
OUT_STEP = HERE / f'ChatGPT_HiLetgo_Level_Shifter_DIN_CableClamp_v{DESIGN_VERSION}.step'
OUT_STL = HERE / f'ChatGPT_HiLetgo_Level_Shifter_DIN_CableClamp_v{DESIGN_VERSION}.stl'

# HiLetgo 4-channel BSS138 level shifter envelope
PCB_LONG = 15.3      # mm, unpopulated ends are clipped
PCB_SHORT = 12.6     # mm, board overhangs the 6 mm mount width
PCB_T = 1.6
PCB_EDGE_CLEAR = 0.30
PCB_THICK_CLEAR = 0.25

source = cq.importers.importStep(str(SOURCE)).val()

# 1) Remove the two cable-rest / cable-tie prongs from the middle of the original
#    part while preserving the original 35 mm DIN snap geometry at both ends.
#    The original spine begins at about Y=4.75 mm, so stop the cut at Y=4.55.
prong_cut = (
    cq.Workplane('XY')
    .box(8.0, 11.75, 27.0, centered=(True, True, True))
    .translate((0, -1.325, 0))  # Y range approx -7.2 .. 4.55
    .val()
)
base = source.cut(prong_cut)

# 2) The original model has two rectangular cable-tie slots through the spine.
#    Fill them flush because this remix does not use cable ties.
#    These are based on the exact section bounds in the supplied STEP.
slot_fill_1 = (
    cq.Workplane('XY').box(6.0, 2.0, 5.0, centered=(True, True, True))
    .translate((0, 7.0, -7.5)).val()
)
slot_fill_2 = (
    cq.Workplane('XY').box(6.0, 2.0, 5.0, centered=(True, True, True))
    .translate((0, 7.0, 17.5)).val()
)
base = base.fuse(slot_fill_1).fuse(slot_fill_2)

# 3) PCB cradle. The board lies in the X-Z plane, with its 15.3 mm dimension
#    across the DIN rail (Z). The 12.6 mm dimension runs along the rail (X), so
#    the PCB simply overhangs the 6 mm-wide printed clip on each side. This keeps
#    all printable geometry within the original 6 mm thickness and lets the part
#    print on either broad X face with no support generated by the PCB cradle.
board_half_z = PCB_LONG / 2
wall_inner_z = board_half_z + PCB_EDGE_CLEAR
wall_outer_z = wall_inner_z + 1.50

# Board slot: rear board face rests at Y=0.90. Front retaining lip leaves
# PCB_T + PCB_THICK_CLEAR clearance.
board_rear_y = 0.90
board_front_y = board_rear_y - PCB_T
lip_inner_y = board_front_y - PCB_THICK_CLEAR

# Helper to make an axis-aligned box from min/max coordinates.
def box_xyz(x0, x1, y0, y1, z0, z1):
    return (
        cq.Workplane('XY')
        .box(x1-x0, y1-y0, z1-z0, centered=(True, True, True))
        .translate(((x0+x1)/2, (y0+y1)/2, (z0+z1)/2))
        .val()
    )

# Full 6 mm width, matching the source mount.
x0, x1 = -3.0, 3.0
spine_join_y = 5.15
wall_front_y = -1.35

# Side walls that flex slightly during snap-in.
top_wall = box_xyz(x0, x1, wall_front_y, spine_join_y,
                   wall_inner_z, wall_outer_z)
bot_wall = box_xyz(x0, x1, wall_front_y, spine_join_y,
                   -wall_outer_z, -wall_inner_z)

# Rear support ledges under the two unpopulated PCB end edges.
ledge_overlap = 1.35
ledge_depth = 0.90
rear_ledge_y0 = board_rear_y
rear_ledge_y1 = board_rear_y + ledge_depth

top_rear = box_xyz(x0, x1, rear_ledge_y0, rear_ledge_y1,
                   wall_inner_z - ledge_overlap, wall_inner_z + 0.25)
bot_rear = box_xyz(x0, x1, rear_ledge_y0, rear_ledge_y1,
                   -wall_inner_z - 0.25, -wall_inner_z + ledge_overlap)

# Front retaining lips.
lip_overlap = 1.05
lip_depth = 0.95
front_lip_y0 = lip_inner_y - lip_depth
front_lip_y1 = lip_inner_y

top_lip = box_xyz(x0, x1, front_lip_y0, front_lip_y1,
                  wall_inner_z - lip_overlap, wall_inner_z + 0.25)
bot_lip = box_xyz(x0, x1, front_lip_y0, front_lip_y1,
                  -wall_inner_z - 0.25, -wall_inner_z + lip_overlap)

# Lead-in ramps. Since the whole profile is extruded through X, these ramps print
# in the layer plane when the part lies on its broad side and need no supports.
def ramp_prism(top=True):
    if top:
        pts_yz = [
            (front_lip_y0 - 0.90, wall_inner_z + 0.10),
            (front_lip_y0,        wall_inner_z - lip_overlap),
            (front_lip_y0,        wall_inner_z + 0.25),
            (front_lip_y0 - 0.90, wall_inner_z + 0.25),
        ]
    else:
        pts_yz = [
            (front_lip_y0 - 0.90, -wall_inner_z - 0.10),
            (front_lip_y0,        -wall_inner_z + lip_overlap),
            (front_lip_y0,        -wall_inner_z - 0.25),
            (front_lip_y0 - 0.90, -wall_inner_z - 0.25),
        ]
    # On a YZ workplane, local coordinates are (Y,Z); extrude symmetrically in X.
    wp = cq.Workplane('YZ').polyline(pts_yz).close().extrude(3.0, both=True)
    return wp.val()

top_ramp = ramp_prism(True)
bot_ramp = ramp_prism(False)

result = base
for piece in [top_wall, bot_wall, top_rear, bot_rear, top_lip, bot_lip, top_ramp, bot_ramp]:
    result = result.fuse(piece)

# Clean BRep before export.
result = result.clean()

# Export native STEP and high-quality binary STL.
exporters.export(result, str(OUT_STEP))
exporters.export(result, str(OUT_STL), tolerance=0.03, angularTolerance=0.05)

bb = result.BoundingBox()
print(f'design_version={DESIGN_VERSION}')
print(f'bbox=({bb.xlen:.3f}, {bb.ylen:.3f}, {bb.zlen:.3f}) mm')
print(f'volume={result.Volume():.3f} mm^3')
print(f'solids={len(result.Solids())} faces={len(result.Faces())} edges={len(result.Edges())}')
print(OUT_STEP)
print(OUT_STL)
